# Generated by Django 5.1.1 on 2024-10-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paper Specification Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('uom', models.CharField(choices=[('NO', "No's"), ('ROLL', 'Roll'), ('PCS', 'Pcs'), ('SQM', 'SqM')], max_length=10, verbose_name='Unit of Measurement')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Width (cm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Height (cm)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cost_estimator.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(choices=[('NO', "No's"), ('ROLL', 'Roll'), ('PCS', 'Pcs'), ('SQM', 'SqM')], max_length=10, verbose_name='Unit of Measurement')),
                ('min_order_quantity', models.PositiveIntegerField(verbose_name='Minimum Order Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_estimator.product', verbose_name='Product')),
                ('sizes', models.ManyToManyField(related_name='configurations', to='cost_estimator.productsize', verbose_name='Product Sizes')),
            ],
        ),
        migrations.CreateModel(
            name='PaperConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_output_quantity', models.PositiveIntegerField(verbose_name='Maximum Output Quantity')),
                ('paper_specifications', models.ManyToManyField(to='cost_estimator.paperspecification', verbose_name='Paper Specifications')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_estimator.product', verbose_name='Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_estimator.productsize', verbose_name='Size')),
            ],
        ),
    ]
