# Generated by Django 5.1.1 on 2024-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_estimator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperspecification',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
